name: Hacker Hours
markdown: kramdown
exclude:
  - vendor
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
# https://github.com/jekyll/github-metadata/issues/62
repository: afeld/hackerhours.org
